CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Judge0 CE용 데이터베이스
SELECT 'CREATE DATABASE judge0' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'judge0')\gexec
