// 시드 데이터: 수학 문항 100개 정의
// 각 문항은 LaTeX 본문, 정답, 메타데이터, 연결할 스킬/성취기준/오개념 코드를 포함
import type {
  ItemType,
  FormulaType,
  AnswerFormat,
  QualityStatus,
} from "@prisma/client";

export interface ItemDef {
  readonly code: string;
  readonly bodyLatex: string;
  readonly answer: { readonly value: string; readonly format: string };
  readonly grade: number;
  readonly itemType: ItemType;
  readonly formulaType: FormulaType;
  readonly answerFormat: AnswerFormat;
  readonly difficultyAuthor: number;
  readonly status: QualityStatus;
  readonly skillCodes: readonly string[];
  readonly standardCodes: readonly string[];
  readonly misconceptionCodes: readonly string[];
}

/** 수학 문항 100개 */
export const ITEMS: readonly ItemDef[] = [
  // ── 수와 연산 (NUM) 20문항 ──
  { code: "ITEM-001", bodyLatex: "$(-3) + 7$의 값을 구하시오.", answer: { value: "4", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["NUM-001"], standardCodes: ["KR2022-M1-NUM-02"], misconceptionCodes: [] },
  { code: "ITEM-002", bodyLatex: "$(-5) \\times (-4)$의 값을 구하시오.", answer: { value: "20", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["NUM-001"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["negative_multiplication"] },
  { code: "ITEM-003", bodyLatex: "$(-2)^3 + 3 \\times (-1)$의 값을 구하시오.", answer: { value: "-11", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-002"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["negative_exponent_sign"] },
  { code: "ITEM-004", bodyLatex: "$\\frac{2}{3} + \\frac{1}{4}$의 값을 구하시오.", answer: { value: "11/12", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-004"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["fraction_addition_numerator_only"] },
  { code: "ITEM-005", bodyLatex: "60을 소인수분해하시오.", answer: { value: "2^2 * 3 * 5", format: "expression" }, grade: 1, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-005"], standardCodes: ["KR2022-M1-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-006", bodyLatex: "24와 36의 최대공약수를 구하시오.", answer: { value: "12", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-005", "NUM-006"], standardCodes: ["KR2022-M1-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-007", bodyLatex: "8과 12의 최소공배수를 구하시오.", answer: { value: "24", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "reviewed", skillCodes: ["NUM-006"], standardCodes: ["KR2022-M1-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-008", bodyLatex: "$\\frac{3}{5} - \\frac{1}{3} + \\frac{2}{15}$의 값을 구하시오.", answer: { value: "2/5", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "reviewed", skillCodes: ["NUM-004"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["fraction_addition_numerator_only"] },
  { code: "ITEM-009", bodyLatex: "$0.\\overline{3}$을 기약분수로 나타내시오.", answer: { value: "1/3", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-003"], standardCodes: ["KR2022-M2-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-010", bodyLatex: "$\\sqrt{50}$을 간단히 하시오.", answer: { value: "5\\sqrt{2}", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-007", "NUM-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-011", bodyLatex: "$\\sqrt{12} + \\sqrt{27}$의 값을 구하시오.", answer: { value: "5\\sqrt{3}", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["NUM-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: ["square_root_of_sum"] },
  { code: "ITEM-012", bodyLatex: "$\\sqrt{2}$가 무리수인 이유를 설명하시오.", answer: { value: "순환하지 않는 무한소수", format: "exact_value" }, grade: 3, itemType: "essay", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "reviewed", skillCodes: ["NUM-008"], standardCodes: ["KR2022-M3-NUM-02"], misconceptionCodes: [] },
  { code: "ITEM-013", bodyLatex: "$\\sqrt{5}$와 $\\sqrt{8}$ 사이에 있는 자연수를 모두 구하시오.", answer: { value: "3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["NUM-010"], standardCodes: ["KR2022-M3-NUM-02"], misconceptionCodes: [] },
  { code: "ITEM-014", bodyLatex: "$\\frac{\\sqrt{18}}{\\sqrt{2}}$의 값을 구하시오.", answer: { value: "3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-015", bodyLatex: "$(-1)^{10} + (-1)^{11}$의 값을 구하시오.", answer: { value: "0", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "draft", skillCodes: ["NUM-001", "NUM-002"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["negative_exponent_sign"] },
  { code: "ITEM-016", bodyLatex: "다음 중 유리수가 아닌 것은?\\\\(1) $0.5$ \\quad (2) $\\sqrt{4}$ \\quad (3) $\\sqrt{3}$ \\quad (4) $\\frac{7}{3}$", answer: { value: "3", format: "multiple_choice" }, grade: 3, itemType: "multiple_choice", formulaType: "mixed", answerFormat: "multiple_choice", difficultyAuthor: 2, status: "approved", skillCodes: ["NUM-008"], standardCodes: ["KR2022-M3-NUM-02"], misconceptionCodes: [] },
  { code: "ITEM-017", bodyLatex: "$2^3 \\times 2^5$를 거듭제곱으로 나타내시오.", answer: { value: "2^8", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 1, status: "approved", skillCodes: ["EXP-004"], standardCodes: ["KR2022-M2-NUM-02"], misconceptionCodes: ["exponent_addition"] },
  { code: "ITEM-018", bodyLatex: "$(3^2)^3$을 거듭제곱으로 나타내시오.", answer: { value: "3^6", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-004"], standardCodes: ["KR2022-M2-NUM-02"], misconceptionCodes: ["exponent_addition"] },
  { code: "ITEM-019", bodyLatex: "$(-3) \\div \\frac{1}{2} \\times (-4)$의 값을 구하시오.", answer: { value: "24", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "draft", skillCodes: ["NUM-002", "NUM-004"], standardCodes: ["KR2022-M1-NUM-03"], misconceptionCodes: ["negative_multiplication"] },
  { code: "ITEM-020", bodyLatex: "$\\sqrt{3}(\\sqrt{12} - \\sqrt{3})$의 값을 구하시오.", answer: { value: "3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "reviewed", skillCodes: ["NUM-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: ["square_root_of_sum"] },

  // ── 문자와 식 (EXP) 20문항 ──
  { code: "ITEM-021", bodyLatex: "$x = 3$일 때, $2x + 5$의 값을 구하시오.", answer: { value: "11", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["EXP-001"], standardCodes: ["KR2022-M1-EXP-01"], misconceptionCodes: [] },
  { code: "ITEM-022", bodyLatex: "$3(2x - 1) + 4x$를 간단히 하시오.", answer: { value: "10x - 3", format: "expression" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-002"], standardCodes: ["KR2022-M1-EXP-02"], misconceptionCodes: ["distributive_law_omission"] },
  { code: "ITEM-023", bodyLatex: "$(3x^2 + 2x - 1) + (x^2 - 4x + 5)$를 간단히 하시오.", answer: { value: "4x^2 - 2x + 4", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-003"], standardCodes: ["KR2022-M2-EXP-01"], misconceptionCodes: [] },
  { code: "ITEM-024", bodyLatex: "$3xy \\times 2x^2y$를 계산하시오.", answer: { value: "6x^3y^2", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-005"], standardCodes: ["KR2022-M2-EXP-02"], misconceptionCodes: [] },
  { code: "ITEM-025", bodyLatex: "$12a^3b^2 \\div 4ab$를 계산하시오.", answer: { value: "3a^2b", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-005"], standardCodes: ["KR2022-M2-EXP-02"], misconceptionCodes: ["cancel_across_addition"] },
  { code: "ITEM-026", bodyLatex: "$(2x + 1)(3x - 2)$를 전개하시오.", answer: { value: "6x^2 - x - 2", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["EXP-006"], standardCodes: ["KR2022-M2-EXP-03"], misconceptionCodes: ["distributive_law_omission"] },
  { code: "ITEM-027", bodyLatex: "$(a + 3)^2$를 전개하시오.", answer: { value: "a^2 + 6a + 9", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-007"], standardCodes: ["KR2022-M2-EXP-03"], misconceptionCodes: [] },
  { code: "ITEM-028", bodyLatex: "$(x + 5)(x - 5)$를 전개하시오.", answer: { value: "x^2 - 25", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-007"], standardCodes: ["KR2022-M2-EXP-03"], misconceptionCodes: [] },
  { code: "ITEM-029", bodyLatex: "$x^2 + 7x + 12$를 인수분해하시오.", answer: { value: "(x + 3)(x + 4)", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["EXP-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["factoring_sign_error"] },
  { code: "ITEM-030", bodyLatex: "$x^2 - 9$를 인수분해하시오.", answer: { value: "(x + 3)(x - 3)", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-031", bodyLatex: "$2x^2 - 8$을 인수분해하시오.", answer: { value: "2(x + 2)(x - 2)", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "reviewed", skillCodes: ["EXP-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["factoring_sign_error"] },
  { code: "ITEM-032", bodyLatex: "등식 $a = b$이면 $a + c = b + c$인 이유를 설명하시오.", answer: { value: "등식의 양변에 같은 수를 더해도 등식이 성립한다", format: "exact_value" }, grade: 1, itemType: "essay", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "reviewed", skillCodes: ["EXP-009"], standardCodes: ["KR2022-M1-EXP-03"], misconceptionCodes: ["equation_both_sides"] },
  { code: "ITEM-033", bodyLatex: "$a > b$이고 $c < 0$이면 $ac \\square bc$에서 $\\square$에 알맞은 부등호를 쓰시오.", answer: { value: "<", format: "exact_value" }, grade: 1, itemType: "fill_in_blank", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EXP-010"], standardCodes: ["KR2022-M1-EQ-03"], misconceptionCodes: ["inequality_multiply_negative"] },
  { code: "ITEM-034", bodyLatex: "$x = -2$일 때, $x^2 - 3x + 1$의 값을 구하시오.", answer: { value: "11", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "draft", skillCodes: ["EXP-001"], standardCodes: ["KR2022-M1-EXP-01"], misconceptionCodes: ["negative_exponent_sign"] },
  { code: "ITEM-035", bodyLatex: "$(5a - 2b) - (3a - 4b)$를 간단히 하시오.", answer: { value: "2a + 2b", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-003"], standardCodes: ["KR2022-M2-EXP-01"], misconceptionCodes: ["sign_error_transposition"] },
  { code: "ITEM-036", bodyLatex: "사과 $a$개가 든 바구니 3개와 사과 $b$개가 든 상자 2개에 있는 사과의 총 개수를 식으로 나타내시오.", answer: { value: "3a + 2b", format: "expression" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "expression", difficultyAuthor: 1, status: "approved", skillCodes: ["EXP-001"], standardCodes: ["KR2022-M1-EXP-01"], misconceptionCodes: ["variable_as_label"] },
  { code: "ITEM-037", bodyLatex: "$\\frac{6x^4y^3}{2x^2y}$를 간단히 하시오.", answer: { value: "3x^2y^2", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EXP-004", "EXP-005"], standardCodes: ["KR2022-M2-NUM-02", "KR2022-M2-EXP-02"], misconceptionCodes: [] },
  { code: "ITEM-038", bodyLatex: "$(a - 2b)^2$를 전개하시오.", answer: { value: "a^2 - 4ab + 4b^2", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["EXP-007"], standardCodes: ["KR2022-M2-EXP-03"], misconceptionCodes: ["distributive_law_omission"] },
  { code: "ITEM-039", bodyLatex: "$x^2 - 5x + 6$을 인수분해하시오.", answer: { value: "(x - 2)(x - 3)", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["EXP-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["factoring_sign_error"] },
  { code: "ITEM-040", bodyLatex: "$(x + 2)(x^2 - 2x + 4)$를 전개하시오.", answer: { value: "x^3 + 8", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 4, status: "draft", skillCodes: ["EXP-006", "EXP-007"], standardCodes: ["KR2022-M2-EXP-03"], misconceptionCodes: [] },

  // ── 방정식 (EQ) 20문항 ──
  { code: "ITEM-041", bodyLatex: "$2x + 3 = 11$을 풀시오.", answer: { value: "4", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["EQ-001"], standardCodes: ["KR2022-M1-EQ-01"], misconceptionCodes: ["sign_error_transposition"] },
  { code: "ITEM-042", bodyLatex: "$5x - 7 = 3x + 9$를 풀시오.", answer: { value: "8", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-001"], standardCodes: ["KR2022-M1-EQ-01"], misconceptionCodes: ["sign_error_transposition", "equation_both_sides"] },
  { code: "ITEM-043", bodyLatex: "어떤 수의 3배에서 5를 뺀 것이 16이다. 어떤 수를 구하시오.", answer: { value: "7", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-002"], standardCodes: ["KR2022-M1-EQ-02"], misconceptionCodes: [] },
  { code: "ITEM-044", bodyLatex: "연속하는 세 홀수의 합이 75일 때, 가장 작은 수를 구하시오.", answer: { value: "23", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-002"], standardCodes: ["KR2022-M1-EQ-02"], misconceptionCodes: [] },
  { code: "ITEM-045", bodyLatex: "\\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}을 풀시오.", answer: { value: "x=5, y=2", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-003"], standardCodes: ["KR2022-M2-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-046", bodyLatex: "\\begin{cases} 2x + 3y = 12 \\\\ x - y = 1 \\end{cases}을 풀시오.", answer: { value: "x=3, y=2", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-003", "EQ-004"], standardCodes: ["KR2022-M2-EQ-01"], misconceptionCodes: ["system_eq_variable_mix"] },
  { code: "ITEM-047", bodyLatex: "\\begin{cases} y = 2x + 1 \\\\ 3x + y = 11 \\end{cases}을 대입법으로 풀시오.", answer: { value: "x=2, y=5", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-004"], standardCodes: ["KR2022-M2-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-048", bodyLatex: "사과 3개와 배 2개의 가격은 5000원이고, 사과 1개와 배 3개의 가격은 4500원이다. 사과 1개의 가격을 구하시오.", answer: { value: "1000", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-005"], standardCodes: ["KR2022-M2-EQ-02"], misconceptionCodes: [] },
  { code: "ITEM-049", bodyLatex: "$x^2 - 5x + 6 = 0$을 풀시오.", answer: { value: "x=2 또는 x=3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["quadratic_incomplete_solution"] },
  { code: "ITEM-050", bodyLatex: "$x^2 + 4x - 5 = 0$을 풀시오.", answer: { value: "x=1 또는 x=-5", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["factoring_sign_error", "quadratic_incomplete_solution"] },
  { code: "ITEM-051", bodyLatex: "$2x^2 - 3x - 2 = 0$을 근의 공식으로 풀시오.", answer: { value: "x=2 또는 x=-1/2", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 4, status: "approved", skillCodes: ["EQ-007"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-052", bodyLatex: "연속하는 두 자연수의 곱이 72일 때, 두 수를 구하시오.", answer: { value: "8, 9", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-008"], standardCodes: ["KR2022-M3-EQ-02"], misconceptionCodes: [] },
  { code: "ITEM-053", bodyLatex: "직사각형의 세로가 가로보다 3cm 짧고, 넓이가 40cm²일 때, 가로의 길이를 구하시오.", answer: { value: "8", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 4, status: "reviewed", skillCodes: ["EQ-008"], standardCodes: ["KR2022-M3-EQ-02"], misconceptionCodes: [] },
  { code: "ITEM-054", bodyLatex: "$3x - 2 > 7$을 풀시오.", answer: { value: "x > 3", format: "expression" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-009"], standardCodes: ["KR2022-M1-EQ-03"], misconceptionCodes: [] },
  { code: "ITEM-055", bodyLatex: "$-2x + 6 \\geq 0$을 풀시오.", answer: { value: "x \\leq 3", format: "expression" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["EQ-009"], standardCodes: ["KR2022-M1-EQ-03"], misconceptionCodes: ["inequality_multiply_negative"] },
  { code: "ITEM-056", bodyLatex: "\\begin{cases} 2x - 1 > 3 \\\\ x + 2 < 8 \\end{cases}을 풀시오.", answer: { value: "2 < x < 6", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-010"], standardCodes: ["KR2022-M2-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-057", bodyLatex: "$\\frac{x+1}{3} = \\frac{x-2}{2}$를 풀시오.", answer: { value: "8", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "reviewed", skillCodes: ["EQ-001"], standardCodes: ["KR2022-M1-EQ-01"], misconceptionCodes: ["equation_both_sides"] },
  { code: "ITEM-058", bodyLatex: "$x^2 = 16$을 풀시오.", answer: { value: "x=4 또는 x=-4", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["quadratic_incomplete_solution"] },
  { code: "ITEM-059", bodyLatex: "\\begin{cases} 3x + 2y = 8 \\\\ 2x + 3y = 7 \\end{cases}을 풀시오.", answer: { value: "x=2, y=1", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "draft", skillCodes: ["EQ-003"], standardCodes: ["KR2022-M2-EQ-01"], misconceptionCodes: ["system_eq_variable_mix"] },
  { code: "ITEM-060", bodyLatex: "$x^2 - 2x - 15 = 0$을 풀시오.", answer: { value: "x=5 또는 x=-3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["factoring_sign_error"] },

  // ── 함수 (FN) 20문항 ──
  { code: "ITEM-061", bodyLatex: "점 $A(3, -2)$는 제 몇 사분면 위의 점인가?", answer: { value: "4", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["FN-001"], standardCodes: ["KR2022-M1-FN-01"], misconceptionCodes: ["coordinate_axis_swap"] },
  { code: "ITEM-062", bodyLatex: "$f(x) = 3x - 1$일 때, $f(2)$의 값을 구하시오.", answer: { value: "5", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["FN-002"], standardCodes: ["KR2022-M1-FN-02"], misconceptionCodes: [] },
  { code: "ITEM-063", bodyLatex: "$y = 2x + 3$의 그래프에서 $y$절편을 구하시오.", answer: { value: "3", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["FN-003"], standardCodes: ["KR2022-M2-FN-01"], misconceptionCodes: ["linear_function_constant_confusion"] },
  { code: "ITEM-064", bodyLatex: "두 점 $(1, 3)$과 $(4, 9)$를 지나는 일차함수의 기울기를 구하시오.", answer: { value: "2", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-004"], standardCodes: ["KR2022-M2-FN-02"], misconceptionCodes: ["slope_fraction_inversion"] },
  { code: "ITEM-065", bodyLatex: "기울기가 $-3$이고 $y$절편이 $5$인 일차함수의 식을 구하시오.", answer: { value: "y = -3x + 5", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-004"], standardCodes: ["KR2022-M2-FN-02"], misconceptionCodes: [] },
  { code: "ITEM-066", bodyLatex: "일차함수 $y = 2x - 4$의 그래프와 $x$축의 교점의 좌표를 구하시오.", answer: { value: "(2, 0)", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-005"], standardCodes: ["KR2022-M2-FN-03"], misconceptionCodes: [] },
  { code: "ITEM-067", bodyLatex: "두 일차함수 $y = x + 1$과 $y = -x + 5$의 교점의 좌표를 구하시오.", answer: { value: "(2, 3)", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["FN-005"], standardCodes: ["KR2022-M2-FN-03"], misconceptionCodes: [] },
  { code: "ITEM-068", bodyLatex: "1분에 3L씩 물을 채우는 수조에 처음 5L의 물이 있다. $x$분 후 물의 양 $y$L를 식으로 나타내시오.", answer: { value: "y = 3x + 5", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "expression", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-006"], standardCodes: ["KR2022-M2-FN-01"], misconceptionCodes: [] },
  { code: "ITEM-069", bodyLatex: "$y = 2x^2$에서 $x = -1$일 때 $y$의 값을 구하시오.", answer: { value: "2", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["FN-007"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-070", bodyLatex: "$y = -x^2$의 그래프는 위로 볼록한가, 아래로 볼록한가?", answer: { value: "위로 볼록", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["FN-007"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-071", bodyLatex: "$y = (x - 2)^2 + 3$의 꼭짓점의 좌표를 구하시오.", answer: { value: "(2, 3)", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["quadratic_vertex_sign"] },
  { code: "ITEM-072", bodyLatex: "$y = -(x + 1)^2 + 4$의 꼭짓점의 좌표와 축의 방정식을 구하시오.", answer: { value: "꼭짓점 (-1, 4), 축 x=-1", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["FN-008"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["quadratic_vertex_sign"] },
  { code: "ITEM-073", bodyLatex: "$y = x^2 - 4x + 3$을 $y = a(x - p)^2 + q$ 꼴로 변환하시오.", answer: { value: "y = (x - 2)^2 - 1", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["FN-009"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-074", bodyLatex: "$y = -2x^2 + 8x - 5$의 최댓값을 구하시오.", answer: { value: "3", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 4, status: "reviewed", skillCodes: ["FN-010"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-075", bodyLatex: "다음 중 $y$가 $x$의 함수인 것은?\\\\(1) $x^2 + y^2 = 1$ \\quad (2) $y = x + 1$ \\quad (3) $|y| = x$ \\quad (4) $y^2 = x$", answer: { value: "2", format: "multiple_choice" }, grade: 1, itemType: "multiple_choice", formulaType: "mixed", answerFormat: "multiple_choice", difficultyAuthor: 3, status: "approved", skillCodes: ["FN-002"], standardCodes: ["KR2022-M1-FN-02"], misconceptionCodes: [] },
  { code: "ITEM-076", bodyLatex: "$y = -\\frac{1}{2}x + 3$의 그래프에서 $x$절편과 $y$절편을 구하시오.", answer: { value: "x절편: 6, y절편: 3", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["FN-003", "FN-004"], standardCodes: ["KR2022-M2-FN-01", "KR2022-M2-FN-02"], misconceptionCodes: ["linear_function_constant_confusion"] },
  { code: "ITEM-077", bodyLatex: "기울기가 2이고 점 $(1, 5)$를 지나는 일차함수의 식을 구하시오.", answer: { value: "y = 2x + 3", format: "expression" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 3, status: "approved", skillCodes: ["FN-004", "FN-006"], standardCodes: ["KR2022-M2-FN-02"], misconceptionCodes: [] },
  { code: "ITEM-078", bodyLatex: "$y = x^2 - 6x + 5$의 그래프의 $x$절편을 모두 구하시오.", answer: { value: "x=1, x=5", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 3, status: "draft", skillCodes: ["FN-009", "EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: [] },
  { code: "ITEM-079", bodyLatex: "$y = 3(x - 1)^2 - 12$에서 $y = 0$이 되는 $x$의 값을 구하시오.", answer: { value: "x=3 또는 x=-1", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 4, status: "reviewed", skillCodes: ["FN-008", "EQ-006"], standardCodes: ["KR2022-M3-EQ-01"], misconceptionCodes: ["quadratic_incomplete_solution"] },
  { code: "ITEM-080", bodyLatex: "$y = x^2 + 2x + k$의 그래프가 $x$축과 접할 때, 상수 $k$의 값을 구하시오.", answer: { value: "1", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "display", answerFormat: "exact_value", difficultyAuthor: 5, status: "draft", skillCodes: ["FN-009", "EQ-007"], standardCodes: ["KR2022-M3-EQ-01", "KR2022-M3-EQ-02"], misconceptionCodes: [] },

  // ── 기하 (GEO) 20문항 ──
  { code: "ITEM-081", bodyLatex: "두 직선이 만나서 생기는 맞꼭지각의 크기가 같은 이유를 설명하시오.", answer: { value: "평각에서 공통 각을 빼면 같다", format: "exact_value" }, grade: 1, itemType: "essay", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-001"], standardCodes: ["KR2022-M1-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-082", bodyLatex: "평행한 두 직선이 한 직선과 만들 때, 동위각의 크기가 $70°$이면 엇각의 크기를 구하시오.", answer: { value: "70", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-002"], standardCodes: ["KR2022-M1-GEO-02"], misconceptionCodes: [] },
  { code: "ITEM-083", bodyLatex: "삼각형의 세 내각의 합은 몇 도인가?", answer: { value: "180", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["GEO-004"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-084", bodyLatex: "삼각형의 두 내각이 $50°$와 $70°$일 때, 나머지 한 내각의 크기를 구하시오.", answer: { value: "60", format: "exact_value" }, grade: 1, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 1, status: "approved", skillCodes: ["GEO-004"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-085", bodyLatex: "삼각형의 합동 조건 SSS를 설명하시오.", answer: { value: "세 변의 길이가 각각 같으면 합동", format: "exact_value" }, grade: 1, itemType: "essay", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-003", "GEO-005"], standardCodes: ["KR2022-M1-GEO-03"], misconceptionCodes: ["congruence_vs_similarity"] },
  { code: "ITEM-086", bodyLatex: "이등변삼각형에서 꼭지각이 $40°$일 때, 밑각의 크기를 구하시오.", answer: { value: "70", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-004"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-087", bodyLatex: "평행사변형의 대각의 크기가 $120°$일 때, 나머지 각의 크기를 각각 구하시오.", answer: { value: "60, 120, 60", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-006"], standardCodes: ["KR2022-M2-GEO-02"], misconceptionCodes: [] },
  { code: "ITEM-088", bodyLatex: "마름모의 두 대각선의 길이가 6cm와 8cm일 때, 마름모의 넓이를 구하시오.", answer: { value: "24", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-006"], standardCodes: ["KR2022-M2-GEO-02"], misconceptionCodes: [] },
  { code: "ITEM-089", bodyLatex: "닮음비가 $2:3$인 두 삼각형에서 큰 삼각형의 넓이가 $36$cm²일 때, 작은 삼각형의 넓이를 구하시오.", answer: { value: "16", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-007"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: ["congruence_vs_similarity"] },
  { code: "ITEM-090", bodyLatex: "높이 1.5m인 사람의 그림자가 2m이고, 나무의 그림자가 8m일 때, 나무의 높이를 구하시오.", answer: { value: "6", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-008"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-091", bodyLatex: "직각삼각형에서 두 변의 길이가 3, 4일 때, 빗변의 길이를 구하시오.", answer: { value: "5", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: ["pythagorean_any_triangle"] },
  { code: "ITEM-092", bodyLatex: "직각삼각형에서 빗변의 길이가 13이고 한 변의 길이가 5일 때, 나머지 변의 길이를 구하시오.", answer: { value: "12", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "none", answerFormat: "exact_value", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-093", bodyLatex: "한 변의 길이가 $\\sqrt{2}$인 정사각형의 대각선의 길이를 구하시오.", answer: { value: "2", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-009", "GEO-010"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-094", bodyLatex: "좌표평면에서 두 점 $A(1, 2)$와 $B(4, 6)$ 사이의 거리를 구하시오.", answer: { value: "5", format: "exact_value" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-010", "FN-001"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-095", bodyLatex: "세 변의 길이가 5, 12, 13인 삼각형은 직각삼각형인가? 이유를 설명하시오.", answer: { value: "예. 5²+12²=25+144=169=13²", format: "exact_value" }, grade: 3, itemType: "essay", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-009"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: ["pythagorean_any_triangle"] },
  { code: "ITEM-096", bodyLatex: "다음 중 SAS 합동 조건에 해당하는 것은?\\\\(1) 두 변과 그 끼인각 \\quad (2) 두 변과 한 대각 \\quad (3) 두 각과 한 변 \\quad (4) 세 각", answer: { value: "1", format: "multiple_choice" }, grade: 1, itemType: "multiple_choice", formulaType: "none", answerFormat: "multiple_choice", difficultyAuthor: 2, status: "approved", skillCodes: ["GEO-005"], standardCodes: ["KR2022-M1-GEO-03"], misconceptionCodes: [] },
  { code: "ITEM-097", bodyLatex: "삼각형 ABC에서 $\\overline{DE} \\parallel \\overline{BC}$이고, $AD:DB = 2:3$일 때, $DE:BC$를 구하시오.", answer: { value: "2:5", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 4, status: "reviewed", skillCodes: ["GEO-007", "GEO-008"], standardCodes: ["KR2022-M2-GEO-01"], misconceptionCodes: [] },
  { code: "ITEM-098", bodyLatex: "직각삼각형의 두 변이 6cm, 8cm일 때, 빗변을 지름으로 하는 원의 넓이를 구하시오.", answer: { value: "25\\pi", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 4, status: "draft", skillCodes: ["GEO-009", "GEO-010"], standardCodes: ["KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-099", bodyLatex: "평행사변형 ABCD에서 $AB = 6$, $BC = 8$, $\\angle B = 90°$일 때, 대각선 AC의 길이를 구하시오.", answer: { value: "10", format: "exact_value" }, grade: 2, itemType: "short_answer", formulaType: "inline", answerFormat: "exact_value", difficultyAuthor: 3, status: "approved", skillCodes: ["GEO-006", "GEO-009"], standardCodes: ["KR2022-M2-GEO-02", "KR2022-M3-NUM-01"], misconceptionCodes: [] },
  { code: "ITEM-100", bodyLatex: "한 변의 길이가 $a$인 정삼각형의 높이를 구하시오.", answer: { value: "\\frac{\\sqrt{3}}{2}a", format: "expression" }, grade: 3, itemType: "short_answer", formulaType: "inline", answerFormat: "expression", difficultyAuthor: 4, status: "reviewed", skillCodes: ["GEO-004", "GEO-009"], standardCodes: ["KR2022-M2-GEO-01", "KR2022-M3-NUM-01"], misconceptionCodes: [] },
];
